### ISSUE TITLE
Update package to 1.36

### ISSUE THREAD

**Issue by mattcargile** [piotrek-szczygiel/clink-chocolatey#2]
Only seeing `1.2.12` when using `choco info clink-maintained`. I see a file scan flag on [chocolatey.org](https://community.chocolatey.org/packages/clink-maintained#versionhistory) as well.

**Comment by piotrek-szczygiel** [comment]
I submitted v1.3.3 some time ago and it still isn’t accepted for some reason: https://community.chocolatey.org/packages/clink-maintained/1.3.3

I think you can try to install this version using exact version number.

**Comment by mattcargile** [comment]
I ended up using `winget install --exact --id chrisant996.Clink`. Not sure how to handle virus scan problems in Chocolatey. It is complaining about the file coming up on Virus Total I think.

**Comment by piotrek-szczygiel** [comment]
I use winget too actually. Tried updating this package because of people requesting it, but Im not using chocolatey personally anymore.
